# 该操作会将source.copy_from下的路径中指定的数据（文件和目录）复制到字段确定的目标存储库target.copy_to下指定的路径中target.repo.
source:
  copy_from:
    - "build"
    - "src/components"
    - "src/config"
    - "src/directive"
    - "src/enums"
    - "src/hooks"
    - "src/layouts"
    - "src/plugins"
    - "src/settings"
    - "src/store/modules/app.ts"
    - "src/store/modules/locale.ts"
    - "src/store/modules/menu.ts"
    - "src/store/modules/settings.ts"
    - "src/store/modules/tabsbar.ts" 
    - "src/store/modules/user.ts" 
    - "src/utils" 
    - "src/views/about"
    - "src/views/dashboard"
    - "src/views/pages/login"
    - "src/App.vue"
    - "src/env.d.ts"
    - "src/main.ts"
    - "types"
    - "package.json"
    - "vite.config.ts"
    - "vitest.config.ts"
    - "windi.config.ts" 
target:
  # 指定不同于源的目标分支
  repo: "idxiu/demo_template"
  maxsize_commit_MB: 1000
  commit_message: "sync from master..."
  copy_to:
    - "build"
    - "src/components"
    - "src/config"
    - "src/directive"
    - "src/enums"
    - "src/hooks"
    - "src/layouts"
    - "src/plugins"
    - "src/settings"
    - "src/store/modules/app.ts"
    - "src/store/modules/locale.ts"
    - "src/store/modules/menu.ts"
    - "src/store/modules/settings.ts"
    - "src/store/modules/tabsbar.ts" 
    - "src/store/modules/user.ts" 
    - "src/utils" 
    - "src/views/about"
    - "src/views/dashboard"
    - "src/views/pages/login"
    - "src/App.vue"
    - "src/env.d.ts"
    - "src/main.ts"
    - "types"
    - "package.json"
    - "vite.config.ts"
    - "vitest.config.ts"
    - "windi.config.ts" 
  # 列出要删除的路径来请求清理（可以留空）。
  #remove_after_copy: 
