name: sync thin Repo

on:
  push:
    branches:
    - 'master'
  workflow_dispatch:

jobs:
  build:
    name: "Sync to Thin"
    #[self-hosted, Linux, X64]
    runs-on: ubuntu-latest  
    steps:
    - uses: icub-tech-iit/gh-action-repo-selective-sync@v1.0.0
      with:
        recipe-file: '.publish/recipe.yml'
        token-source: ${{ secrets.GITHUB_TOKEN }}
        token-target: ${{ secrets.TARGET_PAT }}
        sudo-passwd: ${{ secrets.SELF_HOSTED_RUNNER_PASSWD }}
